services:

  postgres:
    image: postgres:16
    container_name: expensetracker-db
    restart: always
    environment:
      POSTGRES_DB: expensetracker
      POSTGRES_USER: expensetracker_user
      POSTGRES_PASSWORD: change_me
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expensetracker_user -d expensetracker"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expensetracker-backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/expensetracker
      DB_USER: expensetracker_user
      DB_PASSWORD: change_me
      SPRING_PROFILES_ACTIVE: default

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: expensetracker-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
      
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
